# Bazel file for fastrpc
# Two modules to be exported - fastrpc, cdsp-loader

load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

ddk_headers(
    name = "fastrpc_headers",
    hdrs = glob(["include/linux/*.h"]),
    includes = ["include"],
)

load(":define_modules.bzl", "define_modules")

define_modules("pineapple", "consolidate")

define_modules("pineapple", "gki")

define_modules("blair", "consolidate")

define_modules("blair", "gki")

define_modules("sun", "consolidate")

define_modules("sun", "perf")

define_modules("tuna", "consolidate")

define_modules("tuna", "perf")

define_modules("kera", "consolidate")

define_modules("kera", "perf")

define_modules("niobe", "consolidate")

define_modules("niobe", "gki")

define_modules("monaco", "consolidate")

define_modules("monaco", "perf")

define_modules("parrot", "consolidate")

define_modules("parrot", "gki")

define_modules("waipio", "perf")
