/*
* Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
* SPDX-License-Identifier: GPL-2.0-only
*/

#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM 1
#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_I2C 1
#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_CORE 1
#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_TOUCH 1
#define CONFIG_TOUCHSCREEN_NT36XXX_I2C 1
#define CONFIG_QTS_ENABLE 1
#define CONFIG_TOUCHSCREEN_NT36XXX_LATE_EN 1
