#By default build for CLD
DATARMNET_CORE_PATH := datarmnet/core
KBUILD_EXTRA := RMNET_CORE_INC_DIR=$(KERNEL_SRC)/$(M)/../../$(DATARMNET_CORE_PATH)

RMNET_PERF_TETHER_SELECT := CONFIG_RMNET_PERF_TETHER=m
KBUILD_OPTIONS += $(RMNET_PERF_TETHER_SELECT)
KBUILD_OPTIONS += $(KBUILD_EXTRA) # Extra config if any
KBUILD_EXTRA_SYMBOLS := $(M)/../../$(DATARMNET_CORE_PATH)/Module.symvers

M ?= $(shell pwd)

all:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) modules $(KBUILD_OPTIONS) $(KBUILD_EXTRA_SYMBOLS)

modules_install:
	$(MAKE) INSTALL_MOD_STRIP=1 -C $(KERNEL_SRC) M=$(M) modules_install

clean:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) clean
